
import java.net.Socket;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Timer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Abin
 */
public class ShowMessage extends javax.swing.JFrame {

    /**
     * Creates new form ShowMessage
     */
     private static final String JDBC_DRIVER = "com.mysql.jdbc.Driver";
    private static final String DB_URL = "jdbc:mysql://192.168.0.101:3306/vcr";
    
    private static final String USER = "root";
    private static final String PASS = "root";
    
    Connection conn=null;
    Statement stmt = null;
    
   //PutNotice home = new PutNotice();
    
    private static User user=new User("Abin");
    public ShowMessage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });

        jButton1.setText("send");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("160 characters left");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField1)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
//                jLabel1.setText("160 characters only");
                Class.forName("com.mysql.jdbc.Driver");
               conn = DriverManager.getConnection(DB_URL,USER,PASS);
               String message = jTextField1.getText();
               if(message.length()>160){
                   message = message.substring(0, 159);
//                   System.out.println(message);
                   jLabel1.setText("Limit exceeded. First 160 characters considered.");
               }
               jTextField1.setText("");
               stmt = conn.createStatement();
               String sql;
               sql = "insert into message (sender,text) values (\"" + user.getUsername() + "\",\"" + message + "\")";
               stmt.executeUpdate(sql);
               jLabel1.setText("160 characters left");
            }
            catch (SQLException e)
            {
                System.out.print(e.getMessage());
            } catch (ClassNotFoundException ex) {
             Logger.getLogger(ShowMessage.class.getName()).log(Level.SEVERE, null, ex);
         }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        // TODO add your handling code here:
        char ch = evt.getKeyChar();
        if(ch == '\n'){
            try{
//                jLabel1.setText("160 characters only");
                Class.forName("com.mysql.jdbc.Driver");
               conn = DriverManager.getConnection(DB_URL,USER,PASS);
               String message = jTextField1.getText();
//               System.out.println("Message is " + message);
               if(message.length()>=160){
                   message = message.substring(0, 159);
//                   System.out.println(message);
                   jLabel1.setText("Limit exceeded. First 160 characters considered.");
               }
//               System.out.println(message.length());
               jTextField1.setText("");
               stmt = conn.createStatement();
               String sql;
               sql = "insert into message (sender,text) values (\"" + user.getUsername() + "\",\"" + message + "\")";
               stmt.executeUpdate(sql);
            }
            catch (SQLException e)
            {
                System.out.print(e.getMessage());
            } 
            catch (ClassNotFoundException ex) {
             Logger.getLogger(ShowMessage.class.getName()).log(Level.SEVERE, null, ex);
            }
            jLabel1.setText("160 characters left");
        }
        else
        {
        //jLabel1.setText("160 characters only");
        String message1 = ch + jTextField1.getText();
//        System.out.println(message1);
        if(160 - message1.length() >= 0)
            jLabel1.setText((160 - message1.length()) + " characters left.");
        
        else
            jLabel1.setText(message1.length() - 160 + " characters extra. Will be truncated.");
        }
        
        
        
    }//GEN-LAST:event_jTextField1KeyPressed

    /**
     * @param args the command line arguments
     */
    
    
    
    void receive() throws ClassNotFoundException{
        Connection conn = null;
        Statement stmt = null;
        String[] msg;
        try
        {
               
               //JDBC
               Class.forName("com.mysql.jdbc.Driver");
               
               conn = DriverManager.getConnection(DB_URL,USER,PASS);
               
               
               stmt = conn.createStatement();
               String sql;
               sql = "select * from message";
               ResultSet rs =  stmt.executeQuery(sql);
               
               while(rs.next())
               {
                   DefaultListModel model = (DefaultListModel) jList1.getModel();
                   model.addElement(rs.getString("text"));
                   
               }
               
               
                    
           }
        
        catch(SQLException se)
        {
            se.printStackTrace();
        }
        
        catch(Exception e)
        {
           e.printStackTrace();;
        }
        
        finally
        {
            try
            {
        //                socket.close();
                if(stmt!=null)
                    conn.close();
            }
            
            catch(SQLException se)
            {
                se.printStackTrace();
            }
            catch(Exception e)
            {
                e.printStackTrace();
            }
        }
        
        
       return ;
    
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShowMessage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShowMessage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShowMessage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShowMessage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                   try{ 
                ShowMessage showmessage = new ShowMessage();
                showmessage.setVisible(true);
                showmessage.jList1.setModel(new DefaultListModel());
//                showmessage.receive();
                    Timer timer = new Timer();
                    MessageTimer mt = new MessageTimer(showmessage.jList1,"1993-01-17 17:15:00",showmessage.jScrollPane1);
                    timer.schedule(mt,0,500);
                    
                    }
           catch (Exception ex) 
           {
                    Logger.getLogger(ShowMessage.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            });
      
    
                
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
